output_dir: 'experiments/output'
log_dir: 'experiments/log'
device: 'cuda:0'
dataset:
  name: 'rose'
  root: './'
  augmentation:
    horizontal_flip: True
    vertial_flip: False
    rotation: 10
  train_set: 'trainpre.csv'
  test_set: 'testpre.csv'
  mean: [0.5,0.5,0.5]
  sigma: [0.5,0.5,0.5]

model:
  base: 'densenet_161'
  pretrained: False
  num_output: 2
  image_size: [224,224]
  map_size: 14
  smoothing: True

train:
  batch_size: 10
  optimizer: 'adam'
  lr: 0.001
  num_epochs: 20
  loss:
    beta: 0.5

test:
  batch_size: 10
  score_type: 'pixel' # types = (pixel, binary, combined)
